name: Publish on release
on: 
  # Only run when a new release is made
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        # Check-out the git repository...
      - name: Checkout
        uses: actions/checkout@v3
      - name: echo
        run: echo "${GITHUB_REF##*/}"

        
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 19.X
          registry-url: https://registry.npmjs.org/
        
      - name: Install dependencies
        run: yarn && yarn install
        
      - name: Build
        run: yarn build
        
      - name: pulbish
        run: yarn publish --new-version ${GITHUB_REF##*/}
        
        env:
          # npm account token
          NODE_AUTH_TOKEN: ${{ secrets.NOM_TOKEN }}
          
        
